### PR TITLE
updated files to help run create user commands

### PR DESCRIPTION
**Pull request by clmedders**
**_Delete all details that do not apply to this PR!_**

## Jira ticket (required)
Insert Jira ticket link

## Description (optional)
This Pr will only add in files needed to help with create user scripts 

### Testing steps
1. pull down branch 
2. run `lando start`
3. run `lando retune`
4. cd into `testing`
5. select all tests in the back-end folder and confirm they are passing

### CODE REVIEW

**Comment by clmedders** [comment]
the php lint is failing casue it is missing a script of somesort... 

https://app.circleci.com/pipelines/github/usagov/vote-gov-drupal/506/workflows/a9a5569c-15a0-40bf-8017-c5458eab8302/jobs/943

**Review by nehemiah-abuga — APPROVED** [review]
I have verified that the tests are running successfully.

**Comment by clmedders** [comment]
@rayestrada this is ready for you!

**Comment by rayestrada** [comment]
Closing this. It was merged into #99

**Pull request closed without merging**
