### PR TITLE
VOTE-856: Create and Enable State/Territory node migration and depend…

### PR DESCRIPTION
**Pull request by MakaziMtingwa**
## Jira ticket
[VOTE-856](https://bixal-projects.atlassian.net/browse/VOTE-856)

## Description (optional)
State/Territory node migration.

### Pre-deploy steps
None.
### Post-deploy steps
None.
### Testing steps
**Migration Status**: lando drush ms
**Import state_territory nodes**: lando drush mim state_territory
**import all translated nodes**: lando drush mim state_territory_translations

### CODE REVIEW

**Review by rayestrada — CHANGES_REQUESTED** [review]
I've included some feedback in ticket VOTE-856 to be completed. Thanks.
Also please resolve the merge conflict.

**Review by rayestrada — CHANGES_REQUESTED** [review]
@MakaziMtingwa can you please fix the php linting errors shown in the pipeline?

**Review by rayestrada — CHANGES_REQUESTED** [review]
Additional requested revisions have been noted in the JIRA ticket: VOTE-856.
These need to be completed before moving forward on reviewing this PR.

**Comment by MakaziMtingwa** [comment]
Hi @rayestrada This PR has been updated with your requested changes.

**Review by rayestrada — APPROVED** [review]

**Pull request merged**
