### PR TITLE
VOTE-1177 uninstall migration modules

### PR DESCRIPTION
**Pull request by rayestrada**
## Jira ticket (required)
https://bixal-projects.atlassian.net/browse/VOTE-1177

## Description (optional)
Uninstall migration modules so that static file generation can complete without error.

### Pre-deploy steps
1. run `lando drush pm-uninstall migrate -y`

### Post-deploy steps
1. run `lando retune`

### Testing steps
1. run `lando static` and make sure that it completes

### CODE REVIEW

**Comment by MakaziMtingwa** [comment]
Hi @rayestrada I dont know how you'd like to proceed on this, but the feature branch name **1117** is different from the JIRA ticket **1177**

**Review by MakaziMtingwa — CHANGES_REQUESTED** [review]
As previously stated, this feature branch needs to be updated to 1177.

**NVM**. I can see where the description needs to be update but not the branch title.

**Review by MakaziMtingwa — APPROVED** [review]
Was able to run **lando static** without error.

**Comment by rayestrada** [comment]
Oops, updated the description with the correct link.

**Pull request merged**
